---
- name: Converge
  hosts: all:!"*-openjdk"
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java

- name: Converge
  hosts: "*-openjdk-7-jre"
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_version: 7

- name: Converge
  hosts: "*-openjdk-8-jre"
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_version: 8

- name: Converge
  hosts: "*-openjdk-9-jre"
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_version: 9

- name: Converge
  hosts: "*-openjdk-7-jdk"
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_version: 7
      java_type: jdk

- name: Converge
  hosts: "*-openjdk-8-jdk"
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_version: 8
      java_type: jdk

- name: Converge
  hosts: "*-openjdk-9-jdk"
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_version: 9
      java_type: jdk
