---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-java
      # You can use specific version, depending on the distributions
      # use 7, 8, 9, 10 or 11. (The default is 8, this next line is
      # just an example.
      java_version: 8
      # You can also install multiple versions, but be aware that one
      # version is selected using `alternatives`. /usr/bin/java links
      # to the latest installed version.
    - role: ansible-role-java
      java_version: 9
